modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="ffenchants" #mandatory
version="${file.jarVersion}" #mandatory
displayName="FlashFyre's Enchantments"
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="ffenchants.png" #optional
#credits="" #optional
authors="FlashFyre" #optional
description='''
A mod adding lots of new enchantments to the game.
'''
[[dependencies.ffenchants]] #optional
	modId="forge" #mandatory
	mandatory=true #mandatory
	versionRange="[31,)" #mandatory
	ordering="NONE"
	side="BOTH"
[[dependencies.ffenchants]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.15.2]"
	ordering="NONE"
	side="BOTH"